// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXyvSBcvCKjQkBcdmxEjG8SML0VNqXdo',
    appId: '1:313860276779:web:6b3a7dd4070407ad92e06e',
    messagingSenderId: '313860276779',
    projectId: 'rememberotter',
    authDomain: 'rememberotter.firebaseapp.com',
    storageBucket: 'rememberotter.firebasestorage.app',
    measurementId: 'G-ERBRXNP5PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQRBU-yLTPNl-h3VFUtys_U6l3jUfo6Ro',
    appId: '1:313860276779:android:3cae0dcd6593a9d692e06e',
    messagingSenderId: '313860276779',
    projectId: 'rememberotter',
    storageBucket: 'rememberotter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhPDVDtBhbHw3Xs2FA8EFiUFcs9mpZNUg',
    appId: '1:313860276779:ios:2783620db1b0c6c592e06e',
    messagingSenderId: '313860276779',
    projectId: 'rememberotter',
    storageBucket: 'rememberotter.firebasestorage.app',
    iosBundleId: 'com.rudqlsdla.rememberotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhPDVDtBhbHw3Xs2FA8EFiUFcs9mpZNUg',
    appId: '1:313860276779:ios:dc4d041ecf259d5692e06e',
    messagingSenderId: '313860276779',
    projectId: 'rememberotter',
    storageBucket: 'rememberotter.firebasestorage.app',
    iosBundleId: 'com.rudqlsdla.memocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSXyvSBcvCKjQkBcdmxEjG8SML0VNqXdo',
    appId: '1:313860276779:web:d136d9a6ecea4b6292e06e',
    messagingSenderId: '313860276779',
    projectId: 'rememberotter',
    authDomain: 'rememberotter.firebaseapp.com',
    storageBucket: 'rememberotter.firebasestorage.app',
    measurementId: 'G-P1H8X7M1PD',
  );
}
